[package]
name = "qtm-graph"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "qtm"
path = "src/main.rs"

[dependencies]
quantom_value = { git = "https://github.com/QuantPerm-Labs/Quantom-VALUE" }
tokio = { version = "1", features = ["full"] }
hex = "0.4"
eframe = "0.35.0"